openapi: 3.0.1
info:
  title: EDIToken
  description: EDI Token API
  version: 1.0.0
servers:
  - url: /contract/api/v1
tags:
  - name: Token Information
    description: Token Information and Supply endpoints
  - name: Specification
    description: The Token ERC-20 and API specification
  - name: Staking
    description: The Token ERC-20 Staking API
paths:
  /token:
    get:
      tags:
        - Token Information
      description: Fetch ERC-20 Token Information
      responses:
        200:
          description: Return the request with the specified id snapshot
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Circulating"
        4XX:
          description: Network Connectivity Issue - Unable to Process Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error - Status 5xx
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - Staking
      description: Register a Wallet for Staking
      requestBody:
        description: register a valid ethereum wallet address containing the minimum amount of tokens needed to stake
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Staking"
        required: true
      responses:
        201:
          description: Successfuly Registered Wallet, returns transaction/specified id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        4XX:
          description: Network Issue - Connectivity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: 5xx - not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /token/{id}:
    get:
      tags:
        - Token Information
      parameters:
        - name: id
          in: path
          description: The contract address to retrieve data for
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return the request with the specified id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        4XX:
          description: ERROR 4XX
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: ERROR 5XX
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    Circulating:
      type: object
      properties:
        id:
          type: integer
          example: 611029679
        name:
          type: string
          example: Total Supply
    Error:
      type: object
      additionalProperties: true
    Success:
      type: object
      additionalProperties: true

    Staking:
      title: staking
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: 0xbc80dbfc07d18208690f49dedb759d451b369c60

    Token:
      title: token information
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: 0x79c5a1ae586322a07bfb60be36e1b31ce8c84a1e
